### ISSUE TITLE
Skript Reflect not working & breaking skript completely

### ISSUE THREAD

**Issue by Leopard1415** [SkriptLang/skript-reflect#113]
**Describe the bug**
[01:36:05] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[01:36:05] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[01:36:05] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[01:36:05] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[01:36:05] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[01:36:05] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! Stack trace:
[01:36:05] [Server thread/ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[01:36:05] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[01:36:05] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.Types$3.parse(Types.java:60)
[01:36:05] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.Types$3.parse(Types.java:57)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:468)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.registrations.Classes.parse(Classes.java:497)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:593)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:761)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1275)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:185)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:632)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[01:36:05] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.Skript$1.run(Skript.java:815)
[01:36:05] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:36:05] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[01:36:05] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1114)
[01:36:05] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[01:36:05] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! Version Information:
[01:36:05] [Server thread/ERROR]: #!#!   Skript: 2.7.0-beta3
[01:36:05] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[01:36:05] [Server thread/ERROR]: #!#!     Date: 03:18:03.366646700
[01:36:05] [Server thread/ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[01:36:05] [Server thread/ERROR]: #!#!   Minecraft: 1.20.1
[01:36:05] [Server thread/ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[01:36:05] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.10.0-16-amd64
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! Server platform: Paper
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! Current node: null
[01:36:05] [Server thread/ERROR]: #!#! Current item: null
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! Thread: Server thread
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! Language: english
[01:36:05] [Server thread/ERROR]: #!#! Link parse mode: LENIENT
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! End of Error.
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! 
[01:36:05] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[01:36:05] [Server thread/ERROR]: #!#! 

**To reproduce**
Steps to reproduce the behavior. If applicable, add a script or code snippet here.

**Expected behavior**

**Screenshots**

**Server information**
- skript-reflect: v2.3
- Skript: 2.7.0-beta3
- Bukkit:
- Minecraft: 1.20.1
- Java: 21
- OS:

**Additional context**

**Comment by EquipableMC** [comment]
why are you using 2.7.0-beta3 & skript-reflect 2.3??

**Comment by Leopard1415** [comment]
Because 2.7.0 is what the majority of my server has been coded in, and reflect worked up until recently

**Comment by EquipableMC** [comment]
> Because 2.7.0 is what the majority of my server has been coded in, and reflect worked up until recently

Well for starters, you’re far behind. You’re using a beta. 2.7 has been released for awhile now. Update to 2.7.3, and your skript-reflect is outdated, update it to 2.4.

**Comment by sovdeeth** [comment]
Yes please use the latest stable versions of Skript and Skript-Reflect. If the error persists, please re-open this issue.
