### ISSUE TITLE
Script using skript-reflect throws severe error on load

### ISSUE THREAD

**Issue by ChicknTurtle** [SkriptLang/skript-reflect#114]
**Describe the bug**
Loading a simple script using skript-reflect will throw a severe error in console

**To reproduce**
Steps to reproduce the behavior. If applicable, add a script or code snippet here.
This simple code can create the problem:
```
import:
    org.bukkit.event.vehicle.VehicleMoveEvent

on VehicleMoveEvent:
    broadcast "test"
```

**Expected behavior**
The script should load and function properly

**Screenshots**

**Server information**
- skript-reflect: 2.4
- Skript: 2.9.0-pre1
- Bukkit: 1.21-R0.1-SNAPSHOT
- Minecraft: 1.21
- Java: Java 21 (OpenJDK 64-Bit Server VM 21.0.2+13-LTS)
- OS: Mac OS X 14.4.1 (aarch64)

**Additional context**
Full Error:
```
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! [Skript] Severe Error:
[20:52:28 ERROR]: #!#! Could not load test.sk
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Something went horribly wrong with Skript.
[20:52:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:52:28 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:52:28 ERROR]: #!#! Here is full list of them:
[20:52:28 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) DiSky v4.17.2 SkBee v3.5.6 (https://github.com/ShaneBeee/SkBee) 
[20:52:28 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:52:28 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:52:28 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:52:28 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:52:28 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:52:28 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Stack trace:
[20:52:28 ERROR]: #!#! java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
[20:52:28 ERROR]: #!#!     at skript-reflect.jar//org.skriptlang.reflect.java.elements.events.EvtByReflection.getEventClasses(EvtByReflection.java:135)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:90)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:131)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptEvent.parse(SkriptEvent.java:284)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.structures.StructEvent.init(StructEvent.java:69)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:131)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:200)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:675)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:503)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:424)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:440)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:502)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[20:52:28 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
[20:52:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:52:28 ERROR]: #!#!     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[20:52:28 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:446)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:353)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:340)
[20:52:28 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:335)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:52:28 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:52:28 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:52:28 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449)
[20:52:28 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
[20:52:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[20:52:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Version Information:
[20:52:28 ERROR]: #!#!   Skript: 2.9.0-pre1 (latest)
[20:52:28 ERROR]: #!#!     Flavor: skriptlang-github
[20:52:28 ERROR]: #!#!     Date: 20:43:34.397569300
[20:52:28 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[20:52:28 ERROR]: #!#!   Minecraft: 1.21
[20:52:28 ERROR]: #!#!   Java: 21.0.2 (OpenJDK 64-Bit Server VM 21.0.2+13-LTS)
[20:52:28 ERROR]: #!#!   OS: Mac OS X aarch64 14.4.1
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Server platform: Paper
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Current node: on VehicleMoveEvent: (test.sk, line 5)
[20:52:28 ERROR]: #!#! Current item: null
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Thread: Server thread
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! Language: english
[20:52:28 ERROR]: #!#! Link parse mode: DISABLED
[20:52:28 ERROR]: #!#! 
[20:52:28 ERROR]: #!#! End of Error.
[20:52:28 ERROR]: #!#!
```

**Comment by EquipableMC** [comment]
Does this error still happen when you use the skript-reflect dev build for 2.9? (To find it, join [SkriptLang Testing Community](https://discord.gg/utqmjY4g) then go to 2-9-0-beta1 channel and go to the top of the channel to find that skript-reflect dev build)

**Comment by ChicknTurtle** [comment]
This did fix the issue :)

**Comment by Galaxy1133** [comment]
Hey can you give me the link for that server i am having the same issue

**Comment by ChicknTurtle** [comment]
> Hey can you give me the link for that server i am having the same issue

Should be fine on latest release
https://github.com/SkriptLang/skript-reflect/releases
