### ISSUE TITLE
Broken due to new Registration API

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/skript-reflect#128]
**Describe the bug**
Skript reflect fails to load after the new registration api was added in Skript dev/feature

**To reproduce**
- Build Skript dev/feature
- load up a server with reflect

**Expected behavior**
Plugin should load with no errors

**Screenshots**
```
[16:49:11 INFO]: [skript-reflect] Enabling skript-reflect v2.5.1
[16:49:11 ERROR]: Error occurred while enabling skript-reflect v2.5.1 (Is it up to date?)
java.lang.RuntimeException: org.skriptlang.reflect.java.elements.structures.StructImport generated an exception while loading
	at Skript-2.9.5.jar/org.skriptlang.skript.util.ClassLoader.loadClasses(ClassLoader.java:163) ~[Skript-2.9.5.jar:?]
	at Skript-2.9.5.jar/org.skriptlang.skript.util.ClassLoader.loadClasses(ClassLoader.java:91) ~[Skript-2.9.5.jar:?]
	at Skript-2.9.5.jar/ch.njol.skript.util.Utils.getClasses(Utils.java:216) ~[Skript-2.9.5.jar:?]
	at Skript-2.9.5.jar/ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:75) ~[Skript-2.9.5.jar:?]
	at skript-reflect-2.5.1.jar/com.btk5h.skriptmirror.SkriptMirror.onEnable(SkriptMirror.java:62) ~[skript-reflect-2.5.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-DEV-326104b]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Failed to register a syntax info for 'org.skriptlang.reflect.java.elements.structures.StructImport$ImportHandler'. There must be at least one pattern.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
	at Skript-2.9.5.jar/org.skriptlang.skript.registration.SyntaxInfoImpl.<init>(SyntaxInfoImpl.java:34) ~[Skript-2.9.5.jar:?]
	at Skript-2.9.5.jar/org.skriptlang.skript.registration.DefaultSyntaxInfosImpl$ExpressionImpl.<init>(DefaultSyntaxInfosImpl.java:27) ~[Skript-2.9.5.jar:?]
	at Skript-2.9.5.jar/org.skriptlang.skript.registration.DefaultSyntaxInfosImpl$ExpressionImpl$BuilderImpl.build(DefaultSyntaxInfosImpl.java:82) ~[Skript-2.9.5.jar:?]
	at Skript-2.9.5.jar/ch.njol.skript.Skript.registerExpression(Skript.java:1566) ~[Skript-2.9.5.jar:?]
	at skript-reflect-2.5.1.jar/org.skriptlang.reflect.java.elements.structures.StructImport.<clinit>(StructImport.java:47) ~[skript-reflect-2.5.1.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at Skript-2.9.5.jar/org.skriptlang.skript.util.ClassLoader.loadClasses(ClassLoader.java:157) ~[Skript-2.9.5.jar:?]
	... 16 more
```

**Server information**
- skript-reflect: 2.5.1
- Skript: dev/feature branch
- Bukkit: Paper 1.21.4
- Minecraft: 1.21.4
- Java: `Running Java 22 (OpenJDK 64-Bit Server VM 22.0.2+9; Eclipse Adoptium Temurin-22.0.2+9) on Mac OS X 15.2 (aarch64)`
- OS: macOS

**Additional context**

**Comment by sovdeeth** [comment]
yeah tud's on the case

**Comment by abandonedaccount6235** [comment]
#130 🎉

**Comment by APickledWalrus** [comment]
Fixed in 2.6
