### ISSUE TITLE
Could not load the plugin

### ISSUE THREAD

**Issue by carlodrift** [SkriptLang/skript-reflect#29]
```cmd
Could not load 'plugins\skript-reflect-2.1.0 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-655]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-655]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-655]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-655]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-655]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-655]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

**Server information**
- skript-reflect: 2.1.0
- Skript: 2.5-beta2
- Paper: git-Paper-655
- Minecraft: 1.13.2
- Java: 1.8.0_261
- OS: Windows 10

**Comment by TPGamesNL** [comment]
Try with https://github.com/TPGamesNL/skript-reflect/actions/runs/229977497

**Comment by carlodrift** [comment]
> Try with https://github.com/TPGamesNL/skript-reflect/actions/runs/229977497

Yup, it works!

**Comment by carlodrift** [comment]
> Try with https://github.com/TPGamesNL/skript-reflect/actions/runs/229977497

Perhaps a public patch should be deployed? Artifact download has expired.

**Comment by TPGamesNL** [comment]
Yea I wanted to push a release quite some time ago already, but I got less free time, so it was delayed. I do still plan to release soon, with some new features, but in the meantime, here's the file: [skript-reflect-2.1.0.zip](https://github.com/TPGamesNL/skript-reflect/files/5653796/skript-reflect-2.1.0.zip)
