### ISSUE TITLE
return won't work

### ISSUE THREAD

**Issue by eyp57** [SkriptLang/skript-reflect#53]
When I try the 

```
option nms:
    get: 
        set {_nmsversion} to Bukkit.getServer().getClass().getPackage().getName().split("\.")[3]
        return {_nmsversion}
```

It consoles output a error when I reload the skript

[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! [Skript] Severe Error:
[15:50:08 ERROR]: #!#! Could not load GPClaimInteg.sk
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Something went horribly wrong with Skript.
[15:50:08 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:50:08 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:50:08 ERROR]: #!#! Here is full list of them:
[15:50:08 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.2.2 (https://github.com/APickledWalrus/skript-gui) SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 AuctionMaster v4.0 (https://discord.gg/nchk86TKMT)
[15:50:08 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:50:08 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:50:08 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:50:08 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:50:08 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:50:08 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Stack trace:
[15:50:08 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: io.github.apickledwalrus.skriptgui.elements.effects.EffCancelGUIClose
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:228)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getItemsFromNode(SkriptUtil.java:88)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomConstantSection.lambda$init$2(CustomConstantSection.java:66)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.handleEntriesAndSections(CustomSyntaxSection.java:253)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomConstantSection.init(CustomConstantSection.java:58)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:214)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:182)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1101)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[15:50:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:50:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:50:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[15:50:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[15:50:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:50:08 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: invalid parse mark at 9 [pattern: cancel|1Â¦uncancel]
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:114)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:83)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[15:50:08 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getItemsFromNode(SkriptUtil.java:88)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomConstantSection.lambda$init$2(CustomConstantSection.java:66)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.handleEntriesAndSections(CustomSyntaxSection.java:253)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomConstantSection.init(CustomConstantSection.java:58)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:214)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:182)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1101)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[15:50:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:50:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:50:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[15:50:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[15:50:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:50:08 ERROR]: #!#! Caused by: java.lang.NumberFormatException: For input string: "1Â"
[15:50:08 ERROR]: #!#!     at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[15:50:08 ERROR]: #!#!     at java.base/java.lang.Integer.parseInt(Integer.java:668)
[15:50:08 ERROR]: #!#!     at java.base/java.lang.Integer.parseInt(Integer.java:786)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:112)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:83)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[15:50:08 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getItemsFromNode(SkriptUtil.java:88)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomConstantSection.lambda$init$2(CustomConstantSection.java:66)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.handleEntriesAndSections(CustomSyntaxSection.java:253)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomConstantSection.init(CustomConstantSection.java:58)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:214)
[15:50:08 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:182)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1101)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[15:50:08 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[15:50:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:50:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:50:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[15:50:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[15:50:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Version Information:
[15:50:08 ERROR]: #!#!   Skript: 2.6.1 (latest)
[15:50:08 ERROR]: #!#!     Flavor: skriptlang-github
[15:50:08 ERROR]: #!#!     Date: 22:18:42.554713200
[15:50:08 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[15:50:08 ERROR]: #!#!   Minecraft: 1.18.1
[15:50:08 ERROR]: #!#!   Java: 17.0.3 (OpenJDK 64-Bit Server VM 17.0.3+7)
[15:50:08 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Server platform: Paper
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Current node: return {_nmsversion} (GPClaimInteg.sk, line 12)
[15:50:08 ERROR]: #!#! Current item: null
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Thread: Server thread
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! Language: english
[15:50:08 ERROR]: #!#! Link parse mode: DISABLED
[15:50:08 ERROR]: #!#!
[15:50:08 ERROR]: #!#! End of Error.
[15:50:08 ERROR]: #!#!

**Comment by TPGamesNL** [comment]
This is an issue with skript-gui:
> pattern compiling exception, element class: **io.github.apickledwalrus.skriptgui**.elements.effects.EffCancelGUIClose

You should update it: https://github.com/APickledWalrus/skript-gui/releases
