### ISSUE TITLE
skript 2.7.0-beta.1 support

### ISSUE THREAD

**Issue by SpookFloch** [SkriptLang/skript-reflect#63]
Skript-reflect 2.3.0 does not work with skript 2.7.0-beta.1
pls fix :)))

**Comment by TPGamesNL** [comment]
In the meantime, use the addon patcher: https://github.com/SkriptLang/AddonPatcher (at time of writing no releases, feel free to compile yourself, otherwise a release should come in a few days)

If you do try it, lmk if everything works with it, I don't remember

**Comment by SpookFloch** [comment]
Doesn't seem to work with AddonPatcher either

**Comment by TPGamesNL** [comment]
Can you let me know what errors you're getting with AddonPatcher, or what isn't working?

**Comment by SpookFloch** [comment]
Like even after using AddonPatcher on it, it still wont work with skript 2.7.0
It loads up fine but when you try to use anything from reflect, it just sends hella errors to console 

also doesnt seem like AddonPatcher has been updated for like 3 months so that might be outdated


[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! [Skript] Severe Error:
[07:22:31 ERROR]: #!#! Unexpected error while executing effect command 'send {-e}.remove()' by 'CONSOLE'
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Something went horribly wrong with Skript.
[07:22:31 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[07:22:31 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[07:22:31 ERROR]: #!#! Here is full list of them:
[07:22:31 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.9.0 SkBee v2.7.8-for-Skript-2.7.0-beta1 (https://github.com/ShaneBeee/SkBee) 
[07:22:31 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[07:22:31 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[07:22:31 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[07:22:31 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[07:22:31 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[07:22:31 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Stack trace:
[07:22:31 ERROR]: #!#! ch.njol.skript.SkriptAPIException: This ParserInstance is not currently parsing/loading something!
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.parser.ParserInstance.getCurrentScript(ParserInstance.java:131)
[07:22:31 ERROR]: #!#!     at reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[07:22:31 ERROR]: #!#!     at reflect.jar//com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.init(ExprJavaCall.java:137)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:531)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:760)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1273)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.lang.Effect.parse(Effect.java:76)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:212)
[07:22:31 ERROR]: #!#!     at Skript-2.7.0-beta1(1).jar//ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:162)
[07:22:31 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[07:22:31 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[07:22:31 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:22:31 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680)
[07:22:31 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:531)
[07:22:31 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[07:22:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[07:22:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[07:22:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[07:22:31 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Version Information:
[07:22:31 ERROR]: #!#!   Skript: 2.7.0-beta1 (latest)
[07:22:31 ERROR]: #!#!     Flavor: skriptlang-github
[07:22:31 ERROR]: #!#!     Date: 20:28:50.750636200
[07:22:31 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[07:22:31 ERROR]: #!#!   Minecraft: 1.19.3
[07:22:31 ERROR]: #!#!   Java: 17.0.6 (OpenJDK 64-Bit Server VM 17.0.6+10)
[07:22:31 ERROR]: #!#!   OS: Linux amd64 4.19.0-17-amd64
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Server platform: Paper
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Current node: null
[07:22:31 ERROR]: #!#! Current item: null
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Thread: Server thread
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! Language: english
[07:22:31 ERROR]: #!#! Link parse mode: DISABLED
[07:22:31 ERROR]: #!#! 
[07:22:31 ERROR]: #!#! End of Error.
[07:22:31 ERROR]: #!#! 
[07:22:31 INFO]: An internal error occurred while executing this effect. Please refer to the server log for details.

**Comment by APickledWalrus** [comment]
Addon Patcher has been fixed at https://github.com/SkriptLang/AddonPatcher/pull/1

**Comment by TPGamesNL** [comment]
Addon patcher has a release now, use that: https://github.com/SkriptLang/AddonPatcher/releases/tag/2.7.0-dev1

**Comment by TPGamesNL** [comment]
PS, the error above was fixed in Skript 2.7.0-beta2

**Comment by L3v3lup** [comment]
This seems to be broken again with -beta3.

```[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! [Skript] Severe Error:
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Something went horribly wrong with Skript.
[13:41:03 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:41:03 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:41:03 ERROR]: #!#! Here is full list of them:
[13:41:03 ERROR]: #!#! skRayFall v1.9.28 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) ItemsAdder v3.5.0-r2 (devs.beer) skript-yaml v1.4.1-for-MC-1.20 SkBee v2.13.0 (https://github.com/ShaneBeee/SkBee) SkUniversal v2.13 skript-db v1.3.6
[13:41:03 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:41:03 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:41:03 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:41:03 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:41:03 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:41:03 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Stack trace:
[13:41:03 ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[13:41:03 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[13:41:03 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.init(CustomImport.java:82)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:97)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:117)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:185)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:632)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[13:41:03 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.Skript$1.run(Skript.java:815)
[13:41:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:41:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[13:41:03 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1128)
[13:41:03 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:41:03 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Version Information:
[13:41:03 ERROR]: #!#!   Skript: 2.7.0-beta3
[13:41:03 ERROR]: #!#!     Flavor: skriptlang-github
[13:41:03 ERROR]: #!#!     Date: 03:18:03.366646700
[13:41:03 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[13:41:03 ERROR]: #!#!   Minecraft: 1.20.1
[13:41:03 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7-LTS)
[13:41:03 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Server platform: Paper
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Current node: null
[13:41:03 ERROR]: #!#! Current item: null
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Thread: Server thread
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! Language: english
[13:41:03 ERROR]: #!#! Link parse mode: STRICT
[13:41:03 ERROR]: #!#!
[13:41:03 ERROR]: #!#! End of Error.```

**Comment by TPGamesNL** [comment]
@L3v3lup are you using the addonpatcher (linked above)?

**Comment by L3v3lup** [comment]
Oh sorry, i must have missed that. That is working fine. Thank you.

**Comment by TPGamesNL** [comment]
Issues above have been fixed (https://github.com/TPGamesNL/skript-reflect/commit/b52e75f376b742511c32510b82327d64c3d8174e and https://github.com/TPGamesNL/skript-reflect/commit/6982b6110821923a3ad76d7e4b97f8e46bcb7a03), branch `skript-2.7`

If there are further issues on Skript 2.7 (without addon patcher) lmk

**Comment by friyes** [comment]
Seems like it's back with the same error,
`[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! [Skript] Severe Error:

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Something went horribly wrong with Skript.

[10:34:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.

[10:34:46 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).

[10:34:46 ERROR]: #!#! Here is full list of them:

[10:34:46 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4.1-for-MC-1.20 

[10:34:46 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.

[10:34:46 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.

[10:34:46 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.

[10:34:46 ERROR]: #!#! In that case, you will be given instruction on how should you report it.

[10:34:46 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.

[10:34:46 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Stack trace:

[10:34:46 ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'

[10:34:46 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)

[10:34:46 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.init(CustomImport.java:82)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:97)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:117)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:184)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:654)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)

[10:34:46 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)

[10:34:46 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)

[10:34:46 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)

[10:34:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007)

[10:34:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)

[10:34:46 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)

[10:34:46 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)

[10:34:46 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2342)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2302)

[10:34:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)

[10:34:46 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)

[10:34:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)

[10:34:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)

[10:34:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)

[10:34:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)

[10:34:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)

[10:34:46 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Version Information:

[10:34:46 ERROR]: #!#!   Skript: 2.7.1

[10:34:46 ERROR]: #!#!     Flavor: skriptlang-github

[10:34:46 ERROR]: #!#!     Date: 15:04:11.832253

[10:34:46 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT

[10:34:46 ERROR]: #!#!   Minecraft: 1.20.1

[10:34:46 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)

[10:34:46 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Server platform: Paper

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Current node: null

[10:34:46 ERROR]: #!#! Current item: null

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Thread: Server thread

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! Language: english

[10:34:46 ERROR]: #!#! Link parse mode: DISABLED

[10:34:46 ERROR]: #!#! 

[10:34:46 ERROR]: #!#! End of Error.

[10:34:46 ERROR]: #!#! `
