### ISSUE TITLE
Unable to reload script

### ISSUE THREAD

**Issue by nicermak** [SkriptLang/skript-reflect#64]
**Describe the bug**
Unable to reload script with
-server restart
-/sk reload all
**To reproduce**
1. start server
2. there is the error

**Expected behavior**
reload script successfully

**Screenshots**
<img width="411" alt="image" src="https://user-images.githubusercontent.com/83115535/227759751-e15a6cdf-9c44-47cc-b2f2-aa500de98dfa.png">

**Server information**
- skript-reflect: 2.3
- Skript: 2.7.0-beta1
- Bukkit: git-Paper-307
- Minecraft: 1.19.2
- Java: 17.0.1
- OS: Ubuntu 20.04.3 LTS (amd64)

**Additional context**
console log:
```
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! [Skript] Severe Error:
[06:29:52 ERROR]: #!#! Exception occurred in Skript's main command
[06:29:52 ERROR]: #!#! Used command: /sk reload all
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Something went horribly wrong with Skript.
[06:29:52 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:29:52 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:29:52 ERROR]: #!#! Here is full list of them:
[06:29:52 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) 
[06:29:52 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:29:52 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:29:52 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:29:52 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:29:52 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:29:52 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Stack trace:
[06:29:52 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.command.ScriptCommand.unregisterHelp()" because "scriptCommand" is null
[06:29:52 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands.unregisterCommand(Commands.java:290)
[06:29:52 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.structures.StructCommand.unload(StructCommand.java:324)
[06:29:52 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:810)
[06:29:52 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[06:29:52 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:29:52 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[06:29:52 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[06:29:52 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[06:29:52 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[06:29:52 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[06:29:52 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2294)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[06:29:52 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[06:29:52 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[06:29:52 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[06:29:52 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[06:29:52 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[06:29:52 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1289)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1177)
[06:29:52 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[06:29:52 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Version Information:
[06:29:52 ERROR]: #!#!   Skript: 2.7.0-beta1 (latest)
[06:29:52 ERROR]: #!#!     Flavor: skriptlang-github
[06:29:52 ERROR]: #!#!     Date: 20:28:50.750636200
[06:29:52 ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[06:29:52 ERROR]: #!#!   Minecraft: 1.19.2
[06:29:52 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[06:29:52 ERROR]: #!#!   OS: Linux amd64 5.15.0-53-generic
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Server platform: Paper
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Current node: null
[06:29:52 ERROR]: #!#! Current item: null
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Thread: Server thread
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! Language: english
[06:29:52 ERROR]: #!#! Link parse mode: DISABLED
[06:29:52 ERROR]: #!#! 
[06:29:52 ERROR]: #!#! End of Error.
[06:29:52 ERROR]: #!#! 
```

**Comment by nicermak** [comment]
Unsupport skript version
