### ISSUE TITLE
Cannot load Custom Classes

### ISSUE THREAD

**Issue by yhdev7935** [SkriptLang/skript-reflect#71]
**Describe the bug**
Cannot load Custom Classes

**To reproduce**
```
event "evt_A":
    pattern:
        on A event
    event-values: player

command /evtAtest:
    trigger:
        set {_values::player} to player
        call custom event "evt_A" with {_values::*}

on A event:
    message "Hello" to player
```

**Expected behavior**
print Hello

**Screenshots**
```
[02:28:29 ERROR]: #!#! [Skript] Severe Error:
[02:28:29 ERROR]: #!#! Could not load Test\class_test.sk
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Something went horribly wrong with Skript.
[02:28:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:28:29 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[02:28:29 ERROR]: #!#! Here is full list of them:
[02:28:29 ERROR]: #!#! SkriptJSON v1.0.0 skJson v2.8.6 (https://github.com/SkJsonTeam/skJson) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) MorkazSk v1.3 SkJade v1.4.3 (https://www.github.com/Ankoki-Dev/SkJade) ItemsAdder v3.4.0c-beta (devs.beer) Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet) SkBee v2.15.1 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.9
[02:28:29 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[02:28:29 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[02:28:29 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[02:28:29 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[02:28:29 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[02:28:29 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Stack trace:
[02:28:29 ERROR]: #!#! java.lang.ClassCastException: class ch.njol.skript.config.SectionNode cannot be cast to class ch.njol.skript.config.EntryNode (ch.njol.skript.config.SectionNode and ch.njol.skript.config.EntryNode are in unnamed module of loader 'Skript-2.7.0-beta3.jar' @1bf94284)
[02:28:29 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.event.CustomEventSection.init(CustomEventSection.java:78)
[02:28:29 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:214)
[02:28:29 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:182)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:97)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:117)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:185)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:632)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[02:28:29 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
[02:28:29 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:28:29 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:28:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[02:28:29 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[02:28:29 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[02:28:29 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:28:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:28:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[02:28:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[02:28:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1448)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[02:28:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:28:29 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Version Information:
[02:28:29 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[02:28:29 ERROR]: #!#!     Flavor: skriptlang-github
[02:28:29 ERROR]: #!#!     Date: 03:18:03.366646700
[02:28:29 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[02:28:29 ERROR]: #!#!   Minecraft: 1.18.2
[02:28:29 ERROR]: #!#!   Java: 17.0.7 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-224)
[02:28:29 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Server platform: Paper
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Current node: event "evt_A": (Test\class_test.sk, line 1)
[02:28:29 ERROR]: #!#! Current item: null
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Thread: Server thread
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! Language: english
[02:28:29 ERROR]: #!#! Link parse mode: DISABLED
[02:28:29 ERROR]: #!#!
[02:28:29 ERROR]: #!#! End of Error.
[02:28:29 ERROR]: #!#!
```

**Server information**
- skript-reflect: 
- Skript: 2.7.0-beta3
- Bukkit: Paper 1.18.2 388 build
- Minecraft: 1.18.2
- Java: 17.0.17
- OS: Windows

**Comment by TPGamesNL** [comment]
You need 'pattern**s**' in your custom event:
```
event "evt_A":
    patterns:
        on A event
    event-values: player
```

the single form 'pattern' can also be used, but then you shouldn't make a new block from it:
```
event "evt_A":
    pattern: on A event
    event-values: player
```

**Comment by yhdev7935** [comment]
I solved this problem, Thank you!
